//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIM.Properties.BResources", typeof(BResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose any one of the following backups:.
        /// </summary>
        public static string ChooseBackup {
            get {
                return ResourceManager.GetString("ChooseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; database already exists.
        /// </summary>
        public static string DatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("DatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0} xml element is missing.
        /// </summary>
        public static string ElementMissing {
            get {
                return ResourceManager.GetString("ElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong with extracted files.
        /// </summary>
        public static string ExtractedDataIsWrong {
            get {
                return ResourceManager.GetString("ExtractedDataIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; file is missing.
        /// </summary>
        public static string FileIsMissing {
            get {
                return ResourceManager.GetString("FileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; folder already contains subfolder with the &apos;{1}&apos; name.
        /// </summary>
        public static string FolderContainsSubfolder {
            get {
                return ResourceManager.GetString("FolderContainsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location folder path must be physical i.e. contain a drive letter. Please choose another location folder.
        /// </summary>
        public static string FolderNotPhysical {
            get {
                return ResourceManager.GetString("FolderNotPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \Website\App_Config\Include folder doesn&apos;t exist.
        /// </summary>
        public static string IncludeFolderNotExist {
            get {
                return ResourceManager.GetString("IncludeFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; instance can&apos;t be found.
        /// </summary>
        public static string InstanceNotFound {
            get {
                return ResourceManager.GetString("InstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Root Folder isn&apos;t specified in the Settings dialog.
        /// </summary>
        public static string InstancesFolderIsMissing {
            get {
                return ResourceManager.GetString("InstancesFolderIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License isn&apos;t specified in the Settings dialog.
        /// </summary>
        public static string LicenseIsMissing {
            get {
                return ResourceManager.GetString("LicenseIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore installs isn&apos;t specified in the Settings dialog.
        /// </summary>
        public static string LocalRepositoryIsMissing {
            get {
                return ResourceManager.GetString("LocalRepositoryIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no backups to restore.
        /// </summary>
        public static string NoBackupsToRestore {
            get {
                return ResourceManager.GetString("NoBackupsToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; product zip install package can&apos;t be found.
        /// </summary>
        public static string ProductPackageNotFound {
            get {
                return ResourceManager.GetString("ProductPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring isn&apos;t possible due to missing backup files.
        /// </summary>
        public static string RestoringNotPossibleDueToMissingBackupFiles {
            get {
                return ResourceManager.GetString("RestoringNotPossibleDueToMissingBackupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Connection String isn&apos;t set in the Settings dialog.
        /// </summary>
        public static string SqlConnectionStringIsMissing {
            get {
                return ResourceManager.GetString("SqlConnectionStringIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website with the same name already exists, please choose another instance name..
        /// </summary>
        public static string WebsiteAlreadyExists {
            get {
                return ResourceManager.GetString("WebsiteAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; xml file is not well-formatted.
        /// </summary>
        public static string XmlFileIsCorrupted {
            get {
                return ResourceManager.GetString("XmlFileIsCorrupted", resourceCulture);
            }
        }
    }
}
